### PR TITLE
Adding monochrome app icon for Android 13 

### PR DESCRIPTION
**Pull request by JignasP**

### CODE REVIEW

**Comment by JignasP** [comment]
Addressing #208 . @mjaun please look into the PR.

**Comment by mjaun** [comment]
Thanks for your contribution and sorry for my late reaction. There seems to be a problem with the build, can you check this please?

```
AndroidManifest.xml:17: error: resource mipmap/ic_launcher_round (aka ch.logixisland.anuto:mipmap/ic_launcher_round) not found.
```

**Comment by JignasP** [comment]
Renamed ic_launcher_round to icon_round.Please check if this change works.

**Comment by mjaun** [comment]
Sorry but it is still not building.

**Pull request closed without merging**
